spring.data.mongodb.host=localhost
spring.data.mongodb.port=11111
spring.data.mongodb.database=db


spring.graphql.schema.printer.enabled=true

spring.graphql.websocket.path=/graphql

logging.level.org.springframework.graphql=debug
logging.level.graphql=debug