server:
  port: 8081

logging:
  level:
    graphql: debug
    org:
      springframework:
        graphql: debug
spring:
  data:
    mongodb:
      database: db
      host: localhost
      port: 11111
  graphql:
    schema:
      printer:
        enabled: true
    websocket:
      path: /graphql

      
--- 
spring:
  config:
    activate:
      on-profile:
      - replica

  data:
    mongodb:
      database: db
      host: localhost
      port: 11112      
      
server:
  port: 9081
  

  data:
    mongodb:
      database: db
      host: localhost
      port: 11112